language: node_js
# cache:
# directories:
#    - ~/.npm
notifications:
  email: false
node_js:
#  - '6' # comment out until we solve the awaiting problem
  - '8'
  - '9'
before_script:
  - npm prune
  - git diff
script:
  - npm run prepush
  - git status
  - git diff
    # get the coverage metrics to coveralls
  - npm run coveralls-report
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
